#!/bin/bash
# ******************************************
# Program: PRO Autoscript Servis 
# Website: MASTA.VPS
# Developer: SAMREY STEVEN
# Nickname: @ORANGKUATSABAHANTERKINI
# Date: 22-07-2016
# Last Updated: 02-09-2017
# ******************************************
# MULA SETUP
myip=`ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0' | head -n1`;
myint=`ifconfig | grep -B1 "inet addr:$myip" | head -n1 | awk '{print $1}'`;
if [ $USER != 'root' ]; then
echo "Sorry, for run the script please using root user"
exit 1
fi
if [[ "$EUID" -ne 0 ]]; then
echo "Sorry, you need to run this as root"
exit 2
fi
if [[ ! -e /dev/net/tun ]]; then
echo "TUN is not available"
exit 3
fi
echo "
AUTOSCRIPT BY @orangkuatsabahanterkini
AMBIL PERHATIAN !!!"
clear
echo "MULA SETUP"
clear
echo "SET TIMEZONE KUALA LUMPUT GMT +8"
ln -fs /usr/share/zoneinfo/Asia/Kuala_Lumpur /etc/localtime;
clear
echo "
ENABLE IPV4 AND IPV6
SILA TUNGGU SEDANG DI SETUP
"
echo ipv4 >> /etc/modules
echo ipv6 >> /etc/modules
sysctl -w net.ipv4.ip_forward=1
sed -i 's/#net.ipv4.ip_forward=1/net.ipv4.ip_forward=1/g' /etc/sysctl.conf
sed -i 's/#net.ipv6.conf.all.forwarding=1/net.ipv6.conf.all.forwarding=1/g' /etc/sysctl.conf
sysctl -p
clear
echo "
MEMBUANG SPAM PACKAGE
"
apt-get -y --purge remove samba*;
apt-get -y --purge remove apache2*;
apt-get -y --purge remove sendmail*;
apt-get -y --purge remove postfix*;
apt-get -y --purge remove bind*;
clear
echo "
"
sh -c 'echo "deb http://download.webmin.com/download/repository sarge contrib" > /etc/apt/sources.list.d/webmin.list'
wget -qO - http://www.webmin.com/jcameron-key.asc | apt-key add -
apt-get update;
apt-get -y autoremove;
apt-get -y install wget curl;
echo "
"
# script
wget -O /etc/pam.d/common-password "https://raw.githubusercontent.com/ehomecore/deb-ubun/master/common-password"
chmod +x /etc/pam.d/common-password
# fail2ban & exim & protection
service exim4 stop;sysv-rc-conf exim4 off;
# webmin
apt-get -y install webmin
sed -i 's/ssl=1/ssl=0/g' /etc/webmin/miniserv.conf
# dropbear
apt-get -y install dropbear
wget -O /etc/default/dropbear "https://raw.githubusercontent.com/ehomecore/deb-ubun/master/dropbear"
echo "/bin/false" >> /etc/shells
echo "/usr/sbin/nologin" >> /etc/shells
# squid3
apt-get -y install squid3
wget -O /etc/squid3/squid.conf "https://raw.githubusercontent.com/ehomecore/deb-ubun/master/squid.conf"
wget -O /etc/squid/squid.conf "https://raw.githubusercontent.com/ehomecore/deb-ubun/master/squid.conf"
sed -i "s/ipserver/$myip/g" /etc/squid3/squid.conf
sed -i "s/ipserver/$myip/g" /etc/squid/squid.conf
# openvpn
apt-get -y install openvpn
wget -O /etc/openvpn/openvpn.tar "https://raw.githubusercontent.com/guardeumvpn/Qwer77/master/openvpn.tar"
cd /etc/openvpn/;tar xf openvpv.tar;rm openvpn.tar
wget -O /etc/rc.local "https://raw.githubusercontent.com/guardeumvpn/Qwer77/master/rc.local";chmod +x /etc/rc.local
#wget -O /etc/iptables.up.rules "http://rzvpn.net/random/iptables.up.rules"
#sed -i "s/ipserver/$myip/g" /etc/iptables.up.rules
#iptables-restore < /etc/iptables.up.rules
# nginx
apt-get -y install nginx php-fpm php-mcrypt php-cli libexpat1-dev libxml-parser-perl
rm /etc/nginx/sites-enabled/default
rm /etc/nginx/sites-available/default
wget -O /etc/php/7.0/fpm/pool.d/www.conf "https://raw.githubusercontent.com/ehomecore/deb-ubun/master/www.conf"
mkdir -p /home/vps/public_html
echo "<pre>Setup by Sabahanterkini | telegram @OrangkuatSabahanterkini | website mastavps.tk</pre>" > /home/vps/public_html/index.php
echo "<?php phpinfo(); ?>" > /home/vps/public_html/info.php
wget -O /etc/nginx/conf.d/vps.conf "https://raw.githubusercontent.com/ehomecore/deb-ubun/master/vps.conf"
sed -i 's/listen = \/var\/run\/php7.0-fpm.sock/listen = 127.0.0.1:9000/g' /etc/php/7.0/fpm/pool.d/www.conf
# etc
wget -O /home/vps/public_html/client.ovpn "https://raw.githubusercontent.com/ehomecore/deb-ubun/master/client.ovpn"
wget -O /home/vps/public_html/client1.ovpn "https://raw.githubusercontent.com/guardeumvpn/Qwer77/master/client1.ovpn"
wget -O /etc/motd "https://raw.githubusercontent.com/guardeumvpn/Qwer77/master/motd"
sed -i 's/AcceptEnv/#AcceptEnv/g' /etc/ssh/sshd_config
sed -i "s/ipserver/$myip/g" /home/vps/public_html/client.ovpn
sed -i "s/ipserver/$myip/g" /home/vps/public_html/client1.ovpn
#useradd -m -g users -s /bin/bash test
#echo "test:test" | chpasswd
echo "UPDATE AND INSTALL COMPLETE COMPLETE 99% BE PATIENT"
rm *.sh;rm *.txt;rm *.tar;rm *.deb;rm *.asc;rm *.zip;rm ddos*;
clear

# download script
cd /usr/bin
wget -O menu "https://raw.githubusercontent.com/mbah009/deb7/master/menu.sh"
wget -O 1 "https://raw.githubusercontent.com/mbah009/deb7/master/user-add.sh"
wget -O 2 "https://raw.githubusercontent.com/mbah009/deb7/master/trial.sh"
wget -O 3 "https://raw.githubusercontent.com/mbah009/deb7/master/user-gen.sh"
wget -O 4 "https://raw.githubusercontent.com/mbah009/deb7/master/user-list.sh"
wget -O 5 "https://raw.githubusercontent.com/mbah009/deb7/master/user-pass.sh"
wget -O 6 "https://raw.githubusercontent.com/mbah009/deb7/master/user-renew.sh"
wget -O 7 "https://raw.githubusercontent.com/mbah009/deb7/master/user-del.sh"
wget -O 8 "https://raw.githubusercontent.com/mbah009/deb7/master/userexpired.sh"
wget -O 9 "https://raw.githubusercontent.com/mbah009/deb7/master/user-expire-list.sh"
wget -O 10 "https://raw.githubusercontent.com/mbah009/deb7/master/delete-user-expire.sh"
wget -O 11 "https://raw.githubusercontent.com/mbah009/deb7/master/user-banned.sh"
wget -O 12 "https://raw.githubusercontent.com/mbah009/deb7/master/user-unbanned.sh"
wget -O 13 "https://raw.githubusercontent.com/mbah009/deb7/master/user-login.sh"
wget -O 14 "https://raw.githubusercontent.com/mbah009/deb7/master/userlimit.sh"
wget -O 15 "https://raw.githubusercontent.com/mbah009/deb7/master/userlimitssh.sh"
wget -O 16 "https://raw.githubusercontent.com/mbah009/deb7/master/ssh-1.sh"
wget -O 17 "https://raw.githubusercontent.com/mbah009/deb7/master/ssh-2.sh"
wget -O 18 "https://raw.githubusercontent.com/mbah009/deb7/master/ps_mem.py"
wget -O 19 "https://raw.githubusercontent.com/mbah009/deb7/master/resvis.sh"
wget -O 20 "https://raw.githubusercontent.com/mbah009/deb7/master/speedtest_cli.py"
wget -O 21 "https://raw.githubusercontent.com/mbah009/deb7/master/benchmark.sh"
wget -O 22 "https://raw.githubusercontent.com/mbah009/deb7/master/info.sh"
wget -O 23 "https://raw.githubusercontent.com/mbah009/deb7/master/about.sh"
wget -O 24 "https://raw.githubusercontent.com/mbah009/deb7/master/rebootserver.sh"
wget "https://raw.githubusercontent.com/mbah009/deb7/master/autokill.sh"
wget "https://raw.githubusercontent.com/mbah009/deb7/master/autokillssh.sh"
wget "https://raw.githubusercontent.com/mbah009/deb7/master/userlimit.sh"
wget "https://raw.githubusercontent.com/mbah009/deb7/master/userlimitssh.sh"
screen -AmdS check /usr/bin/autokill.sh
screen -AmdS check /usr/bin/autokillssh.sh
sed -i '$ i\screen -AmdS check /usr/bin/autokill.sh' /etc/rc.local
sed -i '$ i\screen -AmdS check /usr/bin/autokillssh.sh' /etc/rc.local
sed -i '$ i\touch /var/lock/subsys/local' /etc/rc.local

chmod +x menu
chmod +x 1
chmod +x 2
chmod +x 3
chmod +x 4
chmod +x 5
chmod +x 6
chmod +x 7
chmod +x 8
chmod +x 9
chmod +x 10
chmod +x 11
chmod +x 12
chmod +x 13
chmod +x 14
chmod +x 15
chmod +x 16
chmod +x 17
chmod +x 18
chmod +x 19
chmod +x 20
chmod +x 21
chmod +x 22
chmod +x 23
chmod +x 24
chmod +x autokill.sh
chmod +x autokillssh.sh
chmod +x userlimit.sh
chmod +x userlimitssh.sh
cd
# restart service
service ssh restart
service openvpn restart
service dropbear restart
service nginx restart
service php7.0-fpm restart
service webmin restart
service squid restart
service fail2ban restart
clear
# SELASAI SUDAH BOSS! ( Autoscript sabahanterkini )
echo "========================================"  | tee -a log-install.txt
echo "Service Autoscript Nobita (NOBITA SCRIPT 2017)"  | tee -a log-install.txt
echo "----------------------------------------"  | tee -a log-install.txt
echo ""  | tee -a log-install.txt
echo "nginx : http://$myip:80"   | tee -a log-install.txt
echo "Webmin : http://$myip:10000/"  | tee -a log-install.txt
echo "Squid3 : 8080"  | tee -a log-install.txt
echo "OpenSSH : 22"  | tee -a log-install.txt
echo "Dropbear : 443"  | tee -a log-install.txt
echo "OpenVPN  : TCP 1194 (DAPATKAN OVPN DARI @ORANGKUATSABAHANTERKINI)"  | tee -a log-install.txt
echo "Fail2Ban : [on]"  | tee -a log-install.txt
echo "Timezone : Asia/Kuala_Lumpur"  | tee -a log-install.txt
echo "Menu : type menu to check menu script"  | tee -a log-install.txt
echo ""  | tee -a log-install.txt
echo "----------------------------------------"
echo "LOG INSTALL  --> /root/log-install.txt"
echo "----------------------------------------"
echo "========================================"  | tee -a log-install.txt
echo "      PLEASE REBOOT TO TAKE EFFECT !"
echo "========================================"  | tee -a log-install.txt
cat /dev/null > ~/.bash_history && history -c
